// Code generated by mockery v2.41.0. DO NOT EDIT.

package server

import mock "github.com/stretchr/testify/mock"

// mockShortener is an autogenerated mock type for the shortener type
type mockShortener struct {
	mock.Mock
}

// Short provides a mock function with given fields: link
func (_m *mockShortener) Short(link string) string {
	ret := _m.Called(link)

	if len(ret) == 0 {
		panic("no return value specified for Short")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(link)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// newMockShortener creates a new instance of mockShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockShortener {
	mock := &mockShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
